USE [master]
GO

/****** Object:  Database [UserProfile]    Script Date: 3/31/2020 4:56:29 PM ******/
CREATE DATABASE [UserProfile] ON  PRIMARY 
( NAME = N'UserProfile', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\UserProfile.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UserProfile_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\UserProfile_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserProfile].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserProfile] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserProfile] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserProfile] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserProfile] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserProfile] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserProfile] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UserProfile] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserProfile] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserProfile] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserProfile] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserProfile] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserProfile] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserProfile] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserProfile] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserProfile] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UserProfile] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserProfile] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserProfile] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserProfile] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserProfile] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserProfile] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UserProfile] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserProfile] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UserProfile] SET  MULTI_USER 
GO

ALTER DATABASE [UserProfile] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserProfile] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UserProfile] SET  READ_WRITE 
GO


